title:              Fu Li's homepage
email:              fuli2@illinois.edu
description:        My Blog
author:             Fu Li
baseurl:            ""
url:                ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
